### ISSUE TITLE
Ignore non-problematic files in the destination folder

### ISSUE THREAD

**Issue by inadarei** [inadarei/justgo#1]
Currently Justgo requires the destination folder to be completely empty. This can be annoying if you are working in a freshly created github workspace which will typically have `.git`, `.gitignore` and `README.md`. 

JustGo should consider presence of these three items to be equivalent of folder being empty, in order to provide better user-experience during bootstrapping.

**Comment by cmlicata** [comment]
@inadarei, I see this being problematic [here](https://github.com/inadarei/justgo/blob/master/cmd/justgo/justgo.go#L72) since the intention is to preserve these non-problematic files.  

I think the best solution would be to simply remove the `README.md` file from the archive and remove [this line](https://github.com/inadarei/justgo/blob/master/cmd/justgo/justgo.go#L72) altogether?

What do you think?

**Comment by inadarei** [comment]
I assume you are saying that out of the three one (README) is a problem. In which case I agree.

One of two choices:
1. unzip somewhere else, not at the destination, do cleanup and then move - not my favorite choice
2. if you notice .git, .gitignore and README are already present:
    1. Ignore presence of .git and .gitignore
    2. In case of README - move it to some unique place (e.g. "uuid" and temp folder) do everything as it would be done normally, move it back. Probably a nice opportunity to use defer, by the way.

**Comment by cmlicata** [comment]
@inadarei, ok I will add #2 to my current implementation and submit a PR for review.
